### ISSUE TITLE
Valuate error with DexYCBMV dataset

### ISSUE THREAD

**Issue by zhanxiaopan** [lixiny/POEM#3]
Hi Lixiny，

Thanks for your great work.
I have tried to reproduce the valuate result as your guided.
**$ python scripts/eval.py --cfg config/release/${MODEL}_${DATASET}.yaml -g 0 -b 8 --reload ${PATH_TO_CKPT}**

My valuated cmd based on **DexYCBMV** dataset:
**python scripts/eval.py --cfg config\release\POEM_DexYCBMV.yaml -g 0 -b 8 --reload checkpoints\POEM_DexYCBMV-20230912T110921Z-001\POEM_DexYCBMV\checkpoint\PtEmbedMultiviewStereo.pth.tar --eval_draw draw**

**The error is listed below, could you help to point out the root cause?**

Traceback (most recent call last):
  File "scripts/eval.py", line 96, in <module>
    main_worker(cfg, arg, exp_time)
  File "scripts/eval.py", line 73, in main_worker
    for bidx, batch in enumerate(testbar):
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\asus\.conda\envs\POEM2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "d:\zhanxiaopan\handtracking\poem\poem\lib\datasets\dexycb.py", line 398, in __getitem__
    assert const_v_id != -101, f"Cannot find the constant camera serial {self.CONST_CAM_SERIAL} in the dataset"
AssertionError: Cannot find the constant camera serial **840412060917** in the dataset

**Comment by lixiny** [comment]
I have re-run the script on my system: Ubuntu 22.04. 
This particular error does not occur.

I suggest you to print all the `info["cam_serial"]` before the `if` statement: [line395](https://github.com/lixiny/POEM/blob/5b371094c70a16b77e59e24b540116755b8acda3/lib/datasets/dexycb.py#L395) to see whether the `cam_serial` exist. 

<img width="478" alt="image" src="https://github.com/lixiny/POEM/assets/32672902/a2bbd507-e362-4cb9-a2b7-0a1e471ae148">

For me, the results are: 
```
836212060125
839512060362
840412060917
841412060263
932122060857
932122060861
932122061900
932122062010
```

**Comment by zhanxiaopan** [comment]
Hi Lixiny,

Thanks for your kind response!
I have pull the latest `main ` branch code, and the environment for me is windows conda, but I guess the error is not about ubuntu or windows.

**The generated log diffence between us is:**
it seems that the results is not the same?  is there any diffence between your local code and the remote main branch code？
![image](https://github.com/lixiny/POEM/assets/32933385/e2e6a202-4c3e-44c0-ba16-e1d0ffbd8c27)

Actually, we need fix minor typos for main branch code.
![image](https://github.com/lixiny/POEM/assets/32933385/00df1347-2cd2-4dd8-a9fc-beb23075b94a)



**The DexYCBMV dataset subjects and multiview info list are:**
![image](https://github.com/lixiny/POEM/assets/32933385/b88cf7a0-88d9-4c8e-a21d-e051ddba8711)

After apply the diff you provided, the result for me is listed below:
**841412060263
932122060857
932122060861**

**Comment by lixiny** [comment]
It seems that the data in your local computer is not complete.
In the dexycb data loader, we use a caching strategy to preload dexycb's file index.
However, the length of the dataset in your cached dexycb dataset is different from ours (as shown by the log differences you provided).

Please try deleting common\cache\DexYCB\ and regenerating the cache, then check if the error still occurs.
